### ISSUE TITLE
🙊 Does this support emoji?

### ISSUE THREAD

**Issue by verlok** [Matriz88/new_title#4]
@Matriz88 does your library support emoji?

I mean, can I do...

```js
window.new_title = "👍 This is a great npm library!"
```

If it does, I will abandon `verlok/vanilla-new_title` and adopt your library and forever!

**Comment by Matriz88** [comment]
Sure it does! as you can see from the example here
https://github.com/Matriz88/new_title/blob/master/examples/index.html

Also don't worry... this library will be vanilla forever :D
